/* GLSL for every scene. All imagery is procedural, so the page has no image downloads. */
window.JOURNEY_GLSL = (function () {
  "use strict";

  var quadVert = [
    "varying vec2 vUv;",
    "void main(){ vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }"
  ].join("\n");

  var common = [
    "float hash11(float p){ p = fract(p * .1031); p *= p + 33.33; p *= p + p; return fract(p); }",
    "float hash21(vec2 p){ vec3 p3 = fract(vec3(p.xyx) * .1031); p3 += dot(p3, p3.yzx + 33.33); return fract((p3.x + p3.y) * p3.z); }",
    "float vnoise(vec2 p){",
    "  vec2 i = floor(p), f = fract(p); f = f * f * (3. - 2. * f);",
    "  float a = hash21(i), b = hash21(i + vec2(1., 0.)), c = hash21(i + vec2(0., 1.)), d = hash21(i + vec2(1., 1.));",
    "  return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);",
    "}",
    "float fbm(vec2 p){",
    "  float v = 0., a = .5; mat2 m = mat2(1.6, 1.2, -1.2, 1.6);",
    "  for (int i = 0; i < 5; i++){ v += a * vnoise(p); p = m * p; a *= .5; }",
    "  return v;",
    "}"
  ].join("\n");

  /* ---------- Scene 1 and 2: mountains, pencil drawing, fog ---------- */
  var mountains = [
    "uniform float uTime, uPush, uPencil, uFog, uIntro;",
    "uniform vec2 uRes, uMouse;",
    "varying vec2 vUv;",
    common,
    "float ridge(float x, float seed){",
    "  float v = 0., a = .5, f = 1.;",
    "  for (int i = 0; i < 4; i++){",
    "    float n = 1. - abs(2. * vnoise(vec2(x * f + seed, seed * 1.7)) - 1.);",
    "    v += a * n * n; a *= .5; f *= 2.1;",
    "  }",
    "  return v;",
    "}",
    "void main(){",
    "  vec2 uv = vUv; float asp = uRes.x / uRes.y;",
    "  vec2 sp = vec2(.64, .50);",
    "  // sky",
    "  float y = uv.y;",
    "  vec3 sky = mix(vec3(.17,.20,.31), vec3(.04,.075,.16), smoothstep(.35,.7,y));",
    "  sky = mix(sky, vec3(.012,.024,.058), smoothstep(.62,1.,y));",
    "  vec2 dd = (uv - sp) * vec2(asp, 1.);",
    "  sky += vec3(1.,.5,.18) * exp(-length(dd) * 2.8) * .55 + vec3(1.,.72,.42) * exp(-length(dd) * 9.) * .55;",
    "  vec2 sg = uv * vec2(asp, 1.) * 170.;",
    "  float st = hash21(floor(sg));",
    "  float twk = .6 + .4 * sin(uTime * 1.6 + st * 60.);",
    "  sky += vec3(.9,.95,1.) * step(.9965, st) * smoothstep(.5,.95,uv.y) * twk * .8 * (1. - clamp(exp(-length(dd)*1.4)*1.6, 0., 1.));",
    "  vec3 col = sky;",
    "  float g = 0.;",
    "  for (int i = 0; i < 5; i++){",
    "    float fi = float(i);",
    "    float base = .50 - fi * .095;",
    "    float amp = .17 + fi * .012;",
    "    float freq = 1. + fi * .55;",
    "    float seed = 3.7 * fi + 1.3;",
    "    float z = (1. + uPush * (.05 + .14 * fi)) * (1. + (1. - uIntro) * .03 * (fi + 1.));",
    "    vec2 anc = vec2(.5, .30);",
    "    vec2 q = anc + (uv - anc) / z;",
    "    q.x += uMouse.x * .010 * (fi + .5); q.y += uMouse.y * .006 * (fi + .5);",
    "    float xw = (q.x - .5) * asp;",
    "    float r = ridge(xw * freq, seed);",
    "    float ry = base + amp * (r - .30);",
    "    float d = ry - q.y;",
    "    float aa = 1.4 / uRes.y;",
    "    float inside = smoothstep(-aa, aa, d);",
    "    float e = .01;",
    "    float r2 = ridge((xw + e) * freq, seed);",
    "    float sl = (r2 - r) / e * amp * freq;",
    "    float lit = smoothstep(-.5, 1.5, -sl);",
    "    float sunfall = exp(-pow((xw - (sp.x - .5) * asp) * 1.1, 2.));",
    "    float rim = exp(-max(d, 0.) / .009) * lit * (.35 + .65 * sunfall);",
    "    float shade = fi / 4.;",
    "    vec3 lc = mix(vec3(.19,.24,.38), vec3(.012,.02,.042), pow(shade, .8));",
    "    lc *= .85 + .3 * fbm(vec2(xw * 8., q.y * 12.) + seed);",
    "    lc += vec3(1.,.52,.17) * rim * (1.15 - .1 * fi);",
    "    float litB = smoothstep(-9., 9., -sl);",
    "    lc += vec3(.5,.25,.12) * litB * sunfall * exp(-max(d, 0.) / .035) * .22;",
    "    col = mix(col, lc, inside);",
    "    if (i > 0){",
    "      float md = fbm(vec2(xw * 1.6 + uTime * .015 * (fi + 1.), q.y * 5. + fi)) * exp(-pow((q.y - (base - .03)) / .10, 2.));",
    "      col = mix(col, vec3(.22,.27,.40) + vec3(.25,.12,.04) * sunfall * .5, md * .5);",
    "    }",
    "    // graphite: hatching inside, outline on the ridge",
    "    float ang = .6 + fi * .35;",
    "    vec2 qq = vec2(q.x * asp, q.y);",
    "    float hv = qq.x * cos(ang) + qq.y * sin(ang);",
    "    float stripe = pow(.5 + .5 * sin(hv * (640. - fi * 40.) + fbm(qq * 30.) * 1.2), 6.);",
    "    float litH = smoothstep(-4., 4., -sl);",
    "    float dens = (.25 + .14 * fi) * (1. - .55 * litH) + .35 * smoothstep(.02, .3, d);",
    "    float hatch = stripe * smoothstep(.26, .5, dens + (fbm(qq * 60.) - .5) * .45);",
    "    g = mix(g, hatch * .6, inside);",
    "    float jit = (vnoise(vec2(xw * 120., seed)) - .5) * .0016;",
    "    float line = smoothstep(2. / uRes.y, 0., abs(d + jit)) + .5 * smoothstep(1.6 / uRes.y, 0., abs(d + jit + .004));",
    "    g = max(g, clamp(line, 0., 1.) * .85);",
    "  }",
    "  // pencil on cream paper",
    "  vec2 pq = uv * vec2(asp, 1.);",
    "  vec3 paper = vec3(.935,.905,.83) * (.93 + .09 * fbm(pq * 8.)) * (.97 + .06 * hash21(floor(gl_FragCoord.xy)));",
    "  paper *= 1. - .30 * dot(uv - .5, uv - .5);",
    "  float front = uPencil * 1.6 - (uv.x * .65 + (1. - uv.y) * .25 + (fbm(pq * 2.) - .5) * .35);",
    "  float reveal = smoothstep(0., .22, front);",
    "  float gDraw = g * smoothstep(.04, .3, front - .06);",
    "  vec3 pen = mix(paper, vec3(.13,.13,.15), clamp(gDraw, 0., 1.) * .92);",
    "  col = mix(col, pen, reveal);",
    "  // drifting cloud and fog",
    "  vec3 fogCol = mix(vec3(.60,.65,.76), vec3(.90,.88,.82), uPencil);",
    "  vec2 cp = vec2(uv.x * asp * 1.2 + uTime * .02, uv.y * 1.6 - uTime * .006);",
    "  vec2 w = vec2(fbm(cp * .7 + 1.3), fbm(cp * .7 + 8.1));",
    "  float c1 = fbm(cp + (w - .5) * 1.2);",
    "  float c2 = fbm(cp * 1.9 + vec2(-uTime * .035, 3.) + (w - .5));",
    "  float c = c1 * .65 + c2 * .35;",
    "  float fm = clamp(uFog * 1.9 - (1. - c) * .9, 0., 1.);",
    "  vec3 cloud = fogCol * (.55 + .62 * smoothstep(.22, .78, c)) + vec3(.07) * pow(c2, 2.);",
    "  col = mix(col, cloud, fm);",
    "  gl_FragColor = vec4(col, 1.);",
    "}"
  ].join("\n");

  /* ---------- Scene 3: storm sky, sea ---------- */
  var storm = [
    "uniform float uTime, uPush, uFlash;",
    "uniform vec2 uRes, uMouse;",
    "varying vec2 vUv;",
    common,
    "void main(){",
    "  vec2 uv = vUv; float asp = uRes.x / uRes.y;",
    "  float H = .30;",
    "  vec2 anc = vec2(.5, H);",
    "  vec2 p = anc + (uv - anc) / (1. + uPush * .28);",
    "  p.x += uMouse.x * .012; p.y += uMouse.y * .006;",
    "  vec2 lightPos = vec2(.34, H + .02);",
    "  float y = max(p.y - H, 0.);",
    "  float depth = 1. / (y + .07);",
    "  vec2 P = vec2((p.x - .5) * asp * depth * .22 + uTime * .018, depth * .20 - uTime * .012);",
    "  vec2 w = vec2(fbm(P * .6 + 3.1 + uTime * .01), fbm(P * .6 + 7.7));",
    "  float d = fbm(P + (w - .5) * 1.1);",
    "  float d2 = fbm(P + (w - .5) * 1.1 + vec2(.10, -.06));",
    "  float cover = smoothstep(.30, .72, d + .15 * smoothstep(.2, .9, y));",
    "  float lit = clamp(.5 + (d - d2) * 6., 0., 1.);",
    "  float gl = exp(-length((p - lightPos) * vec2(asp, 1.2)) * 3.2);",
    "  vec3 sky = mix(vec3(.30,.33,.35), vec3(.06,.07,.09), smoothstep(0., .7, y));",
    "  sky += vec3(.9,.9,.85) * gl * .45;",
    "  vec3 cDark = vec3(.055,.065,.08), cLight = vec3(.52,.55,.57);",
    "  vec3 cloud = mix(cDark, cLight, lit * (.25 + .75 * gl + .25 * (1. - smoothstep(0., .5, y))));",
    "  cloud += vec3(.55,.58,.60) * pow(1. - cover, 3.) * cover * 1.2 * gl;",
    "  cloud *= mix(1., .55, smoothstep(.2, .9, y));",
    "  vec3 col = mix(sky, cloud, cover);",
    "  col = mix(col, vec3(.55,.58,.60) * (.55 + .5 * gl), exp(-y * 28.) * .55);",
    "  col += vec3(.45,.50,.60) * uFlash * (.4 + .6 * cover);",
    "  // sea",
    "  float s = max(H - p.y, 0.);",
    "  float dp = 1. / (s + .015);",
    "  vec2 W = vec2((p.x - .5) * asp * dp * .5, dp * .9 + uTime * .35);",
    "  float wv = fbm(vec2(W.x * 2.5, W.y * 1.1));",
    "  float wv2 = fbm(vec2(W.x * 5. + 4., W.y * 2.2 - uTime * .2));",
    "  vec3 sea = mix(vec3(.17,.20,.22), vec3(.015,.025,.035), smoothstep(0., .28, s));",
    "  float glint = exp(-pow((p.x - lightPos.x) * 3.2, 2.)) * exp(-s * 5.);",
    "  sea += vec3(.8,.82,.8) * glint * pow(wv, 2.2) * .9;",
    "  sea += vec3(.5,.55,.58) * smoothstep(.70, .82, wv * .6 + wv2 * .5) * .12 * (1. - smoothstep(0., .2, s));",
    "  sea *= .75 + .5 * wv;",
    "  sea += vec3(.45,.50,.60) * uFlash * .35;",
    "  col = mix(sea, col, step(H, p.y));",
    "  // rain",
    "  float rn = vnoise(vec2(uv.x * asp * 260. + uv.y * 70., uv.y * 9. + uTime * 9.));",
    "  col += vec3(.7,.75,.8) * smoothstep(.86, 1., rn) * .09;",
    "  gl_FragColor = vec4(col, 1.);",
    "}"
  ].join("\n");

  /* ---------- Scene 4: Earth (Three.js sphere) ---------- */
  var noise3 = [
    "float hash31(vec3 p){ p = fract(p * .3183099 + .1); p *= 17.; return fract(p.x * p.y * p.z * (p.x + p.y + p.z)); }",
    "float vn3(vec3 x){",
    "  vec3 i = floor(x), f = fract(x); f = f * f * (3. - 2. * f);",
    "  return mix(mix(mix(hash31(i), hash31(i + vec3(1,0,0)), f.x), mix(hash31(i + vec3(0,1,0)), hash31(i + vec3(1,1,0)), f.x), f.y),",
    "             mix(mix(hash31(i + vec3(0,0,1)), hash31(i + vec3(1,0,1)), f.x), mix(hash31(i + vec3(0,1,1)), hash31(i + vec3(1,1,1)), f.x), f.y), f.z);",
    "}",
    "float fbm3(vec3 p){ float v = 0., a = .5; for (int i = 0; i < 5; i++){ v += a * vn3(p); p = p * 2.03 + vec3(1.7, 9.2, 3.1); a *= .5; } return v; }"
  ].join("\n");

  var globeVert = [
    "varying vec3 vPos; varying vec3 vN; varying vec3 vV;",
    "void main(){",
    "  vPos = position;",
    "  vec4 wp = modelMatrix * vec4(position, 1.);",
    "  vN = normalize(mat3(modelMatrix) * normal);",
    "  vV = normalize(cameraPosition - wp.xyz);",
    "  gl_Position = projectionMatrix * viewMatrix * wp;",
    "}"
  ].join("\n");

  var globeFrag = [
    "uniform float uTime; uniform vec3 uLight;",
    "varying vec3 vPos; varying vec3 vN; varying vec3 vV;",
    noise3,
    "void main(){",
    "  vec3 n = normalize(vN); vec3 v = normalize(vV); vec3 L = normalize(uLight);",
    "  float h = fbm3(vPos * 2.3 + 4.2 + (fbm3(vPos * 1.2) - .5) * .7);",
    "  float land = smoothstep(.50, .535, h);",
    "  float detail = fbm3(vPos * 18.);",
    "  float mnt = fbm3(vPos * 6. + 11.);",
    "  float lat = abs(vPos.y);",
    "  float ice = smoothstep(.82, .93, lat + (detail - .5) * .15);",
    "  vec3 ocean = mix(vec3(.015,.04,.08), vec3(.035,.085,.15), fbm3(vPos * 4.));",
    "  vec3 ground = mix(vec3(.11,.105,.08), vec3(.26,.22,.16), mnt) * (.45 + 1.1 * detail) * (.7 + .6 * fbm3(vPos * 60.));",
    "  ground = mix(ground, vec3(.12,.15,.14), smoothstep(.55, .8, h) * .5);",
    "  vec3 alb = mix(ocean, ground, land);",
    "  alb = mix(alb, vec3(.34,.38,.42), ice * .85);",
    "  float ndl = dot(n, L);",
    "  float dif = smoothstep(-.12, .85, ndl);",
    "  vec3 col = alb * dif * 2.0 + alb * .05;",
    "  vec3 R = reflect(-L, n);",
    "  col += vec3(.7,.8,1.) * pow(max(dot(R, v), 0.), 140.) * (1. - land) * .55 * step(0., ndl);",
    "  float night = smoothstep(.05, -.25, ndl);",
    "  float cityMask = smoothstep(.55, .75, fbm3(vPos * 7. + 3.)) * land * (1. - ice);",
    "  float pts = smoothstep(.80, .9, vn3(vPos * 70.));",
    "  col += vec3(1., .72, .38) * pts * cityMask * night * 1.6;",
    "  float cl = fbm3(vPos * 3.2 + vec3(uTime * .015, 0., uTime * .01));",
    "  col += vec3(.5,.55,.65) * smoothstep(.55, .8, cl) * dif * .22;",
    "  float fr = pow(1. - max(dot(n, v), 0.), 3.2);",
    "  col += vec3(.25,.45,.95) * fr * (.25 + .75 * smoothstep(-.4, .6, ndl)) * 1.1;",
    "  gl_FragColor = vec4(col, 1.);",
    "}"
  ].join("\n");

  var haloFrag = [
    "uniform vec3 uLight;",
    "varying vec3 vPos; varying vec3 vN; varying vec3 vV;",
    "void main(){",
    "  vec3 n = normalize(vN); vec3 v = normalize(vV);",
    "  float b = clamp(-dot(n, v) * 2.4, 0., 1.);",
    "  float i = pow(b, 3.);",
    "  float side = .25 + .75 * smoothstep(-.5, .5, dot(n, normalize(uLight)));",
    "  gl_FragColor = vec4(vec3(.25,.45,.95) * i * side * 1.4, 1.);",
    "}"
  ].join("\n");

  /* ---------- Scene 5: misty forest, golden rays, falling particles ---------- */
  var forest = [
    "uniform float uTime, uPush;",
    "uniform vec2 uRes, uMouse;",
    "varying vec2 vUv;",
    common,
    "void main(){",
    "  vec2 uv = vUv; float asp = uRes.x / uRes.y;",
    "  vec2 anc = vec2(.42, .5);",
    "  vec2 Lp = vec2(.18, 1.12);",
    "  vec3 gold = vec3(1., .80, .42);",
    "  vec3 col = mix(vec3(.10,.17,.14), vec3(.30,.42,.35), smoothstep(0., .6, uv.y));",
    "  for (int i = 0; i < 6; i++){",
    "    float fi = float(i);",
    "    float z = 1. + uPush * (.05 + .10 * fi);",
    "    vec2 q = anc + (uv - anc) / z;",
    "    q.x += uMouse.x * .012 * (fi + .5); q.y += uMouse.y * .005 * (fi + .5);",
    "    vec2 dl = (q - Lp) * vec2(asp, 1.);",
    "    float ang = atan(dl.y, dl.x); float dist = length(dl);",
    "    float rn = vnoise(vec2(ang * 9., uTime * .04 + fi)) * .6 + vnoise(vec2(ang * 22. + fi * 3., -uTime * .035)) * .4;",
    "    float rays = smoothstep(.38, .85, rn) * exp(-dist * 1.05);",
    "    col += gold * rays * .125;",
    "    float freq = 3. + fi * 1.9;",
    "    float x = q.x * asp * freq + fi * 13.7;",
    "    float cell = floor(x);",
    "    float r1 = hash21(vec2(cell, fi * 7.1));",
    "    float r2 = hash21(vec2(cell + 31., fi * 3.3));",
    "    float r3 = hash21(vec2(cell, fi + 90.));",
    "    float lean = (q.y - .5) * (r2 - .5) * .5;",
    "    float cx = cell + .25 + .5 * r1 + lean;",
    "    float wd = (.05 + .07 * r2) * (.6 + fi * .3);",
    "    float dx = abs(x - cx);",
    "    float aa = asp * freq / uRes.x * 1.2;",
    "    float trunk = (1. - smoothstep(wd - aa, wd + aa, dx)) * step(.35, r3);",
    "    float canA = smoothstep(.66, .92, q.y + (fbm(vec2(q.x * asp * 2.5 + fi * 5., q.y * 2.)) - .5) * .4) * step(1.5, fi);",
    "    float cov = max(trunk, canA * .9);",
    "    float shade = fi / 5.;",
    "    vec3 tc = mix(vec3(.10,.19,.16), vec3(.005,.02,.016), pow(shade, .7));",
    "    tc *= .8 + .4 * vnoise(vec2(x * 40., q.y * 3.));",
    "    float t = (x - cx) / wd;",
    "    tc += gold * smoothstep(-.2, -.95, t) * (.12 + rays * 2.5) * (1. - shade * .6);",
    "    tc *= mix(1., .7, canA);",
    "    col = mix(col, tc, cov);",
    "    float md = fbm(vec2(q.x * asp * 1.4 + uTime * .012 * (fi + 1.) + fi * 3., q.y * 3. + fi)) * (.9 - fi * .12);",
    "    col = mix(col, vec3(.34,.46,.40) + gold * rays * .3, clamp(md * .34 * (1. - fi * .1), 0., 1.) * .9);",
    "  }",
    "  col *= mix(.5, 1., smoothstep(0., .4, uv.y));",
    "  vec2 dlg = (uv - Lp) * vec2(asp, 1.);",
    "  col += gold * exp(-length(dlg) * 2.2) * .35;",
    "  float boost = .4 + .9 * exp(-length(dlg) * 1.2);",
    "  for (int k = 0; k < 3; k++){",
    "    float fk = float(k);",
    "    float sc = 16. + fk * 12.;",
    "    vec2 g = vec2(uv.x * asp, uv.y) * sc;",
    "    g.y += uTime * (.35 + .25 * fk);",
    "    g.x += sin(uTime * .25 + fk * 2.) * .6 + uMouse.x * .5 * (fk + 1.);",
    "    vec2 cell = floor(g), f = fract(g);",
    "    float rr = hash21(cell + fk * 37.);",
    "    vec2 off = vec2(hash21(cell + 7.7 + fk), hash21(cell + 3.3 + fk)) * .6 + .2;",
    "    float dd = length(f - off);",
    "    float pt = smoothstep((.05 + .035 * fk) * (.6 + rr), 0., dd) * step(.84, rr) * (.5 + .5 * sin(uTime * 1.5 + rr * 40.));",
    "    col += mix(vec3(1., .9, .6), vec3(1.), .4) * pt * (.35 + .25 * fk) * boost;",
    "  }",
    "  col *= vec3(.96, 1.0, .97);",
    "  gl_FragColor = vec4(col, 1.);",
    "}"
  ].join("\n");

  /* ---------- Compositor: dissolve, dip to black, vignette, film grain ---------- */
  var composite = [
    "uniform sampler2D tA, tB;",
    "uniform float uT, uBlack, uTime, uGrain;",
    "uniform vec2 uRes;",
    "varying vec2 vUv;",
    common,
    "void main(){",
    "  vec2 uv = vUv;",
    "  float n = fbm(uv * vec2(uRes.x / uRes.y, 1.) * 2.6 + uTime * .03);",
    "  float t = clamp(uT, 0., 1.);",
    "  float th = t * 1.3 - .15;",
    "  float m = smoothstep(n - .15, n + .15, th);",
    "  vec2 cA = (uv - .5) * (1. - .04 * t) + .5;",
    "  vec2 cB = (uv - .5) * (1. + .05 * (1. - t)) + .5;",
    "  vec3 col = mix(texture2D(tA, cA).rgb, texture2D(tB, cB).rgb, m);",
    "  col *= 1. - uBlack;",
    "  float vig = 1. - .5 * pow(length((uv - .5) * vec2(1.15, 1.)), 2.4);",
    "  col *= vig;",
    "  float gr = hash21(gl_FragCoord.xy + fract(uTime * 37.) * vec2(113., 71.)) - .5;",
    "  col += gr * uGrain * (.6 + .4 * (1. - dot(col, vec3(.333))));",
    "  gl_FragColor = vec4(col, 1.);",
    "}"
  ].join("\n");

  return {
    quadVert: quadVert,
    mountains: mountains,
    storm: storm,
    forest: forest,
    composite: composite,
    globeVert: globeVert,
    globeFrag: globeFrag,
    haloFrag: haloFrag
  };
})();
